version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      patch-and-minor:
        patterns: ["*"]
        update-types: ["minor", "patch"]
