import Phaser from 'phaser';
import { eventBus } from '../core/EventBus.js';
import { EVENTS,RARITY,GAME } from '../core/Constants.js';
import { gameState } from '../core/GameState.js';
const W=GAME.VIEW_WIDTH,H=GAME.HEIGHT,P=0x08111f,P2=0x102235,M='#9db0c6',ACCENT=0x67d7ff;
export class UISceneV2 extends Phaser.Scene{
 constructor(){super({key:'UIScene',active:false});this.timer=null;this.inventoryPanel=null;this.handlers=[]}
 t(x,y,s,n=8,c='#f5f7fb'){return this.add.text(x,y,s,{fontFamily:'monospace',fontSize:`${n}px`,color:c,stroke:'#02060b',strokeThickness:n>9?2:1,resolution:2}).setScrollFactor(0)}
 create(){this.add.rectangle(0,0,W,22,P,.96).setOrigin(0).setDepth(90);this.add.rectangle(0,21,W,1,ACCENT,.25).setOrigin(0).setDepth(91);this.t(7,5,'TIDEFALL',9,'#d9f4ff').setDepth(100);this.t(66,3,'ENERGY',6,M).setDepth(100);this.add.rectangle(66,14,58,5,0x203448).setOrigin(0,.5).setDepth(100);this.energy=this.add.rectangle(66,14,58,3,0x63e28a).setOrigin(0,.5).setDepth(101);this.fish=this.t(136,4,'FISH 0').setDepth(100);this.gold=this.t(199,4,'0g',8,'#ffd85a').setDepth(100);this.time=this.t(252,5,'DAY',7).setDepth(100);this.weather=this.t(314,5,'CLEAR',7,M).setDepth(100);this.action=this.t(355,5,'SPACE CAST',7,'#b9e9ff').setDepth(100);this.t(355,13,'I BAG',6,M).setDepth(100);this.msgBg=this.add.rectangle(W/2,34,100,15,P,.92).setDepth(98).setVisible(false);this.msg=this.t(W/2,29,'',8,'#d7f7ff').setOrigin(.5,0).setDepth(99).setVisible(false);this.add.rectangle(W/2,H-12,330,16,P,.88).setDepth(90);this.hint=this.t(W/2,H-18,'Walk to the shoreline, then press SPACE to cast.',7,'#d2e0ee').setOrigin(.5,0).setDepth(100);this.catchBg=this.add.rectangle(W/2,78,230,56,P,.97).setDepth(300).setVisible(false);this.catchBorder=this.add.rectangle(W/2,78,232,58).setStrokeStyle(2,0xffffff,.9).setDepth(301).setVisible(false);this.catchFish=this.t(W/2,59,'',12).setOrigin(.5).setDepth(302).setVisible(false);this.catchMeta=this.t(W/2,79,'',8,M).setOrigin(.5).setDepth(302).setVisible(false);this.catchValue=this.t(W/2,95,'',9,'#ffd85a').setOrigin(.5).setDepth(302).setVisible(false);this.touch();this.eventsOn();this.sync()}
 touch(){if(!this.sys.game.device.input.touch)return;const s=()=>this.scene.get('FishingScene'),mv=(d,v)=>{const p=s()?.player;if(p)p.setInputState({...p.input,[d]:v)},b=(x,y,g,a,h)=>{const bg=this.add.rectangle(x,y,28,28,P,.76).setStrokeStyle(1,0x7ea9c2,.7).setInteractive().setDepth(220);this.t(x,y,g,11).setOrigin(.5).setDepth(221);let down=false;bg.on('pointerdown',()=>{down=true;bg.setFillStyle(P2,.94);a?.();h?.(true)});const up=()=>{if(!down)return;down=false;bg.setFillStyle(P,.76);h?.(false)};bg.on('pointerup',up).on('pointerupoutside',up).on('pointerout',up)};b(34,H-47,'←',null,v=>mv('left',v));b(92,H-47,'→',null,v=>mv('right',v));b(63,H-70,'↑',null,v=>mv('up',v));b(63,H-24,'↓',null,v=>mv('down',v));b(W-48,H-48,'F',()=>s()?.handleFishingInput?.());b(W-82,H-81,'E',()=>s()?.handleInteract?.());b(W-114,H-48,'I',()=>this.toggleInventory())}
 eventsOn(){const on=(e,fn)=>{eventBus.on(e,fn);this.handlers.push([e,fn])};on(EVENTS.PLAYER_ENERGY_CHANGE,e=>this.setEnergy(e.energy));on(EVENTS.UI_SHOW_MESSAGE,p=>this.showMessage(typeof p==='object'?p.text:p,typeof p==='object'?(p.duration??2200):2200));on(EVENTS.UI_GOLD_SYNC,p=>{const g=typeof p==='object'?p.gold:p;if(typeof g==='number')this.gold.setText(`${g}g`)});on(EVENTS.UI_TOGGLE_INVENTORY,()=>this.toggleInventory());on(EVENTS.FISHING_BITE,()=>{this.action.setText('SPACE HOOK');this.hint.setText('Fish on! Press SPACE to hook.')});on(EVENTS.FISHING_CATCH,p=>{this.fish.setText(`FISH ${gameState.game.totalCaught}`);this.action.setText('SPACE CAST');this.hint.setText('Catch secured. Find another spot and cast again.');this.showCatch(p.fish,p.weight,p.perfect)});on(EVENTS.TIME_CHANGE,p=>this.time.setText(String(p?.phase||p?.timeOfDay||'day').toUpperCase()));on(EVENTS.WEATHER_CHANGE,p=>this.weather.setText(String(p?.weather||p?.type||'clear').toUpperCase()));this.events.once('shutdown',()=>this.handlers.forEach(([e,fn])=>eventBus.off(e,fn)))}
 sync(){this.setEnergy(gameState.player.energy);this.gold.setText(`${gameState.game.gold}g`);this.fish.setText(`FISH ${gameState.game.totalCaught}`);this.time.setText(String(gameState.game.timeOfDay||'day').toUpperCase());this.weather.setText(String(gameState.game.weather||'clear').toUpperCase())}
 setEnergy(e){const p=Phaser.Math.Clamp(Number(e)/100,0,1);this.energy.setDisplaySize(58*p,3);this.energy.setFillStyle(p>.5?0x63e28a:p>.25?0xf0d36a:0xf07070)}
 showMessage(s,d=2200){if(!s)return;this.msg.setText(String(s)).setVisible(true);this.msgBg.setDisplaySize(Math.min(Math.max(this.msg.width+24,90),430),15).setVisible(true);if(this.timer)this.timer.remove();this.timer=this.time.delayedCall(d,()=>{this.msg.setVisible(false);this.msgBg.setVisible(false)})}
 showCatch(f,w,perfect){if(!f)return;const r=String(f.rarity||'common').toLowerCase(),c=RARITY[r]||'#fff',a=[this.catchBg,this.catchBorder,this.catchFish,this.catchMeta,this.catchValue];this.catchBorder.setStrokeStyle(2,parseInt(c.slice(1),16),.95);this.catchFish.setText(`${perfect?'PERFECT · ':''}${f.name||'Fish'}`).setColor(c);this.catchMeta.setText(`${r.toUpperCase()} · ${Number(w||0).toFixed(2)} kg`);this.catchValue.setText(`+${f.value||10}g`);a.forEach(x=>x.setVisible(true).setAlpha(0));this.tweens.add({targets:a,alpha:1,duration:120});this.time.delayedCall(2100,()=>this.tweens.add({targets:a,alpha:0,duration:160,onComplete:()=>a.forEach(x=>x.setVisible(false))}))}
 toggleInventory(){if(this.inventoryPanel){this.inventoryPanel.destroy(true);this.inventoryPanel=null;return}const inv=this.registry.get('inventory'),fish=inv?.getAllFish?.()||[],p=this.add.container(W/2,H/2).setDepth(320);p.add([this.add.rectangle(0,0,286,176,P,.98),this.add.rectangle(0,0,288,178).setStrokeStyle(2,ACCENT,.8),this.t(0,-76,'CATCH LOG',11,'#d9f4ff').setOrigin(.5),this.t(0,-60,`${fish.length}/${inv?.maxSlots??30} slots`,7,M).setOrigin(.5)]);p.add(this.t(0,-8,fish.length?fish.slice(-9).reverse().map((i,n)=>`${n+1}. ${(i.fish?.name||'Fish').slice(0,14).padEnd(14,' ')} ${Number(i.weight||0).toFixed(1)}kg ${i.fish?.value??0}g`).join('\n'):'Nothing caught yet.\nWalk to the water and cast.',8,M).setOrigin(.5,0));p.add(this.t(0,76,'Press I to close',7,'#6f849a').setOrigin(.5));this.inventoryPanel=p}
}
